FROM node:18-alpine AS builder

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install

COPY . .

ARG VITE_TMDB_API_KEY
ARG VITE_TMDB_ACCESS_TOKEN
ARG VITE_IMAGE_URL
ARG VITE_FIREBASE_API_KEY
ARG VITE_AUTH_DOMAIN
ARG VITE_PROJECT_ID
ARG VITE_STORAGE_BUCKET
ARG VITE_MESSAGING_SENDER_ID
ARG VITE_APP_ID

RUN npm run build

EXPOSE 8080

CMD ["npm", "run", "preview"]
